<?php
acf_add_local_field_group( array(
    'key'                   => 'group_5d2cc3f95f048' ,
    'title'                 => 'Options Contact' ,
    'fields'                => array(
        array(
            'key'               => 'field_5d2cc5c0e8264' ,
            'label'             => 'Conatc Info' ,
            'name'              => '' ,
            'type'              => 'tab' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'placement'         => 'left' ,
            'endpoint'          => 0 ,
        ) ,
        array(
            'key'               => 'field_5d823955qasdf' ,
            'label'             => 'Title Form' ,
            'name'              => 'title_form' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d823955daecf' ,
            'label'             => 'Title Address' ,
            'name'              => 'title_address' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d2cc5ede8266' ,
            'label'             => 'Address' ,
            'name'              => 'address' ,
            'type'              => 'textarea' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'maxlength'         => '' ,
            'rows'              => '' ,
            'new_lines'         => 'br' ,
        ) ,
        array(
            'key'               => 'field_5d823975daed0' ,
            'label'             => 'Title Email' ,
            'name'              => 'title_email_and_mobile' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d2cc5cfezser' ,
            'label'             => 'Email' ,
            'name'              => 'e-mail' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d823975asdfq' ,
            'label'             => 'Title Mobile' ,
            'name'              => 'title_mobile' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d2cc5f8e8267' ,
            'label'             => 'Mobile' ,
            'name'              => 'mobile' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d823a4c3986a' ,
            'label'             => 'Map Options' ,
            'name'              => '' ,
            'type'              => 'tab' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'placement'         => 'left' ,
            'endpoint'          => 0 ,
        ) ,
        array(
            'key'               => 'field_5d82432103cbf' ,
            'label'             => 'show Map' ,
            'name'              => 'show_map' ,
            'type'              => 'true_false' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'message'           => '' ,
            'default_value'     => 1 ,
            'ui'                => 1 ,
            'ui_on_text'        => '' ,
            'ui_off_text'       => '' ,
        ) ,
        array(
            'key'               => 'field_5d823a6b3986b' ,
            'label'             => 'Map' ,
            'name'              => 'map' ,
            'type'              => 'google_map' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d82432103cbf' ,
                        'operator' => '==' ,
                        'value'    => '1' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'center_lat'        => '' ,
            'center_lng'        => '' ,
            'zoom'              => 12 ,
            'height'            => '' ,
        ) ,
        array(
            'key'               => 'field_5d823716bc862' ,
            'label'             => 'option' ,
            'name'              => 'option' ,
            'type'              => 'clone' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'clone'             => array(
                0  => 'field_5d277d7783e23' ,
                1  => 'field_5d2781b83ad7c' ,
                2  => 'field_5d277f7383e24' ,
                3  => 'field_5d28e73b57a3d' ,
                4  => 'field_5d2781a091f9a' ,
                5  => 'field_5d27836b5f452' ,
                6  => 'field_5d7819985dec4' ,
                7  => 'field_5d2784225f454' ,
                8  => 'field_5d7abee14551e' ,
                9  => 'field_5d7abd1a8f4d6' ,
                10 => 'field_5d7abdf68f4d7' ,
                11 => 'field_5d7abe248f4d8' ,
            ) ,
            'display'           => 'seamless' ,
            'layout'            => 'block' ,
            'prefix_label'      => 0 ,
            'prefix_name'       => 0 ,
        ) ,
    ) ,
    'location'              => array(
        array(
            array(
                'param'    => 'post_template' ,
                'operator' => '==' ,
                'value'    => 'page-miao-contact.php' ,
            ) ,
        ) ,
    ) ,
    'menu_order'            => 0 ,
    'position'              => 'normal' ,
    'style'                 => 'default' ,
    'label_placement'       => 'top' ,
    'instruction_placement' => 'label' ,
    'hide_on_screen'        => '' ,
    'active'                => true ,
    'description'           => '' ,
) );


function miao_map_acf_init()
{
    acf_update_setting( 'google_api_key' , get_theme_mod( 'map_api' ) );
}

add_action( 'acf/init' , 'miao_map_acf_init' );