<?php
acf_add_local_field_group( array(
    'key'                   => 'group_5d277c4736814' ,
    'title'                 => 'Options Pages' ,
    'fields'                => array(
        array(
            'key'               => 'field_5d277d7783e23' ,
            'label'             => 'Banner & Title Area' ,
            'name'              => '' ,
            'type'              => 'tab' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'placement'         => 'left' ,
            'endpoint'          => 0 ,
        ) ,
        array(
            'key'               => 'field_5d7816181c1b8' ,
            'label'             => 'Type Nav' ,
            'name'              => 'menu_type' ,
            'type'              => 'radio' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'hamburger-menu' => 'Hamburger Menu' ,
                'Classic-menu'   => 'Classic Menu' ,
            ) ,
            'allow_null'        => 0 ,
            'other_choice'      => 0 ,
            'default_value'     => 'hamburger-menu' ,
            'layout'            => 'horizontal' ,
            'return_format'     => 'value' ,
            'save_other_choice' => 0 ,
        ) ,
        array(
            'key'               => 'field_5d2781b83ad7c' ,
            'label'             => 'Header Type Page' ,
            'name'              => 'header_type' ,
            'type'              => 'select' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'post'   => 'Header With Image' ,
                'normal' => 'Normal Header' ,
                'none'   => 'None' ,
            ) ,
            'default_value'     => array(
                0 => 'post' ,
            ) ,
            'allow_null'        => 0 ,
            'multiple'          => 0 ,
            'ui'                => 0 ,
            'return_format'     => 'value' ,
            'ajax'              => 0 ,
            'placeholder'       => '' ,
        ) ,
        array(
            'key'               => 'field_5d277f7383e24' ,
            'label'             => 'Custom Title' ,
            'name'              => 'custom_title' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d2781b83ad7c' ,
                        'operator' => '!=' ,
                        'value'    => 'none' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d28e73b57a3d' ,
            'label'             => 'SubTitle' ,
            'name'              => 'subtitle' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d2781b83ad7c' ,
                        'operator' => '!=' ,
                        'value'    => 'none' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d2781a091f9a' ,
            'label'             => 'Description Header' ,
            'name'              => 'description_header' ,
            'type'              => 'textarea' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d2781b83ad7c' ,
                        'operator' => '==' ,
                        'value'    => 'normal' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'maxlength'         => '' ,
            'rows'              => '' ,
            'new_lines'         => 'br' ,
        ) ,
        array(
            'key'               => 'field_5d27836b5f452' ,
            'label'             => 'Layout' ,
            'name'              => '' ,
            'type'              => 'tab' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'placement'         => 'top' ,
            'endpoint'          => 0 ,
        ) ,
        array(
            'key'               => 'field_5d7819985dec4' ,
            'label'             => 'Page Layout' ,
            'name'              => 'page_layout' ,
            'type'              => 'button_group' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '!=' ,
                        'value'    => 'project' ,
                    ) ,
                ) ,

            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'full'      => 'Wide Page' ,
                'container' => 'Container Page' ,
                'half'      => 'Half Page' ,
            ) ,
            'allow_null'        => 0 ,
            'default_value'     => 'half' ,
            'layout'            => 'horizontal' ,
            'return_format'     => 'value' ,
        ) ,
        array(
            'key'               => 'field_5d2784225f454' ,
            'label'             => 'Background Color' ,
            'name'              => 'background_color' ,
            'type'              => 'select' ,
            'instructions'      => 'Background color for this page.' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'dark'  => 'Dark' ,
                'light' => 'Light' ,
            ) ,
            'default_value'     => array(
                0 => 'dark' ,
            ) ,
            'allow_null'        => 0 ,
            'multiple'          => 0 ,
            'ui'                => 0 ,
            'return_format'     => 'value' ,
            'ajax'              => 0 ,
            'placeholder'       => '' ,
        ) ,
        array(
            'key'               => 'field_5d2783875f453' ,
            'label'             => 'Show Sidebar' ,
            'name'              => 'show_sidebar' ,
            'type'              => 'select' ,
            'instructions'      => 'if you want your Use Sidebar. (Active Checkbox)' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'show' => 'Show' ,
                'hide' => 'Hide' ,
            ) ,
            'default_value'     => array(
                0 => 'show' ,
            ) ,
            'allow_null'        => 0 ,
            'multiple'          => 0 ,
            'ui'                => 0 ,
            'return_format'     => 'value' ,
            'ajax'              => 0 ,
            'placeholder'       => '' ,
        ) ,
        array(
            'key'               => 'field_5d7abee14551e' ,
            'label'             => 'Navigation' ,
            'name'              => '' ,
            'type'              => 'tab' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'placement'         => 'top' ,
            'endpoint'          => 0 ,
        ) ,
        array(
            'key'               => 'field_5d7abd1a8f4d6' ,
            'label'             => 'Next Page' ,
            'name'              => 'next_page' ,
            'type'              => 'post_object' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'post_type'         => array(
                0 => 'page' ,
                1 => 'mavy-portfolio' ,
                2 => 'post' ,
            ) ,
            'taxonomy'          => '' ,
            'allow_null'        => 0 ,
            'multiple'          => 0 ,
            'return_format'     => 'object' ,
            'ui'                => 1 ,
        ) ,
        array(
            'key'               => 'field_5d7abdf68f4d7' ,
            'label'             => 'Title Next Page' ,
            'name'              => 'title_next_page' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7abd1a8f4d6' ,
                        'operator' => '!=empty' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d7abe248f4d8' ,
            'label'             => 'Subtitle Next Page' ,
            'name'              => 'subtitle_next_page' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7abd1a8f4d6' ,
                        'operator' => '!=empty' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d7ad7627cc90' ,
            'label'             => 'Header Type' ,
            'name'              => 'header_type' ,
            'type'              => 'select' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'project'   => 'Feature Header With Image' ,
                'project-2' => 'Parallax Header' ,
                'post'      => 'Header With Image' ,
                'normal'    => 'Normal Header' ,
                'none'      => 'None' ,
            ) ,
            'default_value'     => array(
                0 => 'project' ,
            ) ,
            'allow_null'        => 0 ,
            'multiple'          => 0 ,
            'ui'                => 0 ,
            'return_format'     => 'value' ,
            'ajax'              => 0 ,
            'placeholder'       => '' ,
        ) ,
        array(
            'key'               => 'field_5d91fc272305e' ,
            'label'             => 'Scale Header' ,
            'name'              => 'scale_header' ,
            'type'              => 'button_group' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'project' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'dsn-header-scale-feature' => 'Scale Effect' ,
                'dsn-header-normal'        => 'Normal' ,
            ) ,
            'allow_null'        => 0 ,
            'default_value'     => 'dsn-header-scale-feature' ,
            'layout'            => 'horizontal' ,
            'return_format'     => 'value' ,
        ) ,
        array(
            'key'               => 'field_5d91fe88784b8' ,
            'label'             => 'Animate Header' ,
            'name'              => 'animate_header' ,
            'type'              => 'button_group' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'project-2' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'dsn-parallax-scale-animate' => 'Scale Effect' ,
                'glitch_effect'              => 'Glitch Effect'
            ) ,
            'allow_null'        => 0 ,
            'default_value'     => 'dsn-parallax-scale-animate' ,
            'layout'            => 'horizontal' ,
            'return_format'     => 'value' ,
        ) ,
        array(
            'key'               => 'field_5d922f97bd74d' ,
            'label'             => 'Glitch Effect Text' ,
            'name'              => 'glitch_effect_text' ,
            'type'              => 'true_false' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'project-2' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'message'           => '' ,
            'default_value'     => 0 ,
            'ui'                => 1 ,
            'ui_on_text'        => '' ,
            'ui_off_text'       => '' ,
        ) ,
        array(
            'key'               => 'field_5d7adee424fbd' ,
            'label'             => 'Custom Title' ,
            'name'              => 'custom_title' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '!=' ,
                        'value'    => 'none' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d7adef224fbe' ,
            'label'             => 'SubTitle' ,
            'name'              => 'subtitle' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'post' ,
                    ) ,
                ) ,
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'normal' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d7adf5124fc1' ,
            'label'             => 'Visit Link' ,
            'name'              => 'visit_link' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'project' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d7ae2e910093' ,
            'label'             => 'Year' ,
            'name'              => 'year' ,
            'type'              => 'text' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'maxlength'         => '' ,
        ) ,
        array(
            'key'               => 'field_5d7adf0224fbf' ,
            'label'             => 'Description Header' ,
            'name'              => 'description_header' ,
            'type'              => 'textarea' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'normal' ,
                    ) ,
                ) ,
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'project' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => '' ,
            'placeholder'       => '' ,
            'maxlength'         => '' ,
            'rows'              => '' ,
            'new_lines'         => 'br' ,
        ) ,
        array(
            'key'               => 'field_5d88dcbb8daa8' ,
            'label'             => 'Pagination' ,
            'name'              => 'ajax_load_more' ,
            'type'              => 'true_false' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'message'           => '' ,
            'default_value'     => 1 ,
            'ui'                => 1 ,
            'ui_on_text'        => 'Ajax' ,
            'ui_off_text'       => 'Number' ,
        ) ,
        array(
            'key'               => 'field_5d8b599a4e186' ,
            'label'             => 'Overlay Background' ,
            'name'              => 'overlay_background' ,
            'type'              => 'range' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5d7ad7627cc90' ,
                        'operator' => '==' ,
                        'value'    => 'project' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => 7 ,
            'min'               => 0 ,
            'max'               => 9 ,
            'step'              => 1 ,
            'prepend'           => '' ,
            'append'            => '' ,
        ) ,
    ) ,
    'location'              => array(
        array(
            array(
                'param'    => 'post_type' ,
                'operator' => '==' ,
                'value'    => 'post' ,
            ) ,
        ) ,
    ) ,
    'menu_order'            => 0 ,
    'position'              => 'normal' ,
    'style'                 => 'default' ,
    'label_placement'       => 'top' ,
    'instruction_placement' => 'label' ,
    'hide_on_screen'        => '' ,
    'active'                => false ,
    'description'           => '' ,
) );