<?php


acf_add_local_field_group( array(
    'key'                   => 'group_5cbe0fe4e8e24' ,
    'title'                 => 'Slider Option' ,
    'fields'                => array(
        array(
            'key'               => 'field_5d7816181c1b8' ,
            'label'             => 'Type Nav' ,
            'name'              => 'menu_type' ,
            'type'              => 'radio' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'hamburger-menu' => 'Hamburger Menu' ,
                'Classic-menu'   => 'Classic Menu' ,
            ) ,
            'allow_null'        => 0 ,
            'other_choice'      => 0 ,
            'default_value'     => 'hamburger-menu' ,
            'layout'            => 'horizontal' ,
            'return_format'     => 'value' ,
            'save_other_choice' => 0 ,
        ) ,
        array(
            'key'               => 'field_5d8243210z1z2' ,
            'label'             => 'All Work' ,
            'name'              => 'all_work' ,
            'type'              => 'true_false' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'message'           => '' ,
            'default_value'     => 0 ,
            'ui'                => 1 ,
            'ui_on_text'        => 'Show' ,
            'ui_off_text'       => 'Hide' ,
        ) ,
        array(
            'key'               => 'field_5cbe0ff7a6c56' ,
            'label'             => 'Views' ,
            'name'              => 'dsn-views' ,
            'type'              => 'radio' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'work'   => 'Works' ,
                'custom' => 'Custom Slide' ,
            ) ,
            'allow_null'        => 0 ,
            'other_choice'      => 0 ,
            'default_value'     => 'work' ,
            'layout'            => 'horizontal' ,
            'return_format'     => 'value' ,
            'save_other_choice' => 0 ,
        ) ,
        array(
            'key'               => 'field_5cbe1151a6c57' ,
            'label'             => 'Layout' ,
            'name'              => 'layout' ,
            'type'              => 'select' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'default' => 'Default' ,
                'box'     => 'Boxed' ,
                'full'    => 'Full' ,
            ) ,
            'default_value'     => array(
                0 => 'default' ,
            ) ,
            'allow_null'        => 0 ,
            'multiple'          => 0 ,
            'ui'                => 0 ,
            'return_format'     => 'value' ,
            'ajax'              => 0 ,
            'placeholder'       => '' ,
        ) ,
        array(
            'key'               => 'field_5cca2dac66ff7' ,
            'label'             => 'Order' ,
            'name'              => 'slid_order' ,
            'type'              => 'radio' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5cbe0ff7a6c56' ,
                        'operator' => '==' ,
                        'value'    => 'work' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'choices'           => array(
                'ASC'  => 'Old To New' ,
                'DESC' => 'New To Old' ,
            ) ,
            'allow_null'        => 0 ,
            'other_choice'      => 0 ,
            'default_value'     => 'ASC' ,
            'layout'            => 'horizontal' ,
            'return_format'     => 'value' ,
            'save_other_choice' => 0 ,
        ) ,
        array(
            'key'               => 'field_5cbe11c6a6c58' ,
            'label'             => 'Maximum Number Of Slider' ,
            'name'              => 'maximum_number_of_slider' ,
            'type'              => 'number' ,
            'instructions'      => 'if you want display all slider	, input number (-1)' ,
            'required'          => 1 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => 10 ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'min'               => -1 ,
            'max'               => '' ,
            'step'              => 1 ,
        ) ,
        array(
            'key'               => 'field_5d2ddeab6d691' ,
            'label'             => 'Background Overlay' ,
            'name'              => 'overlay' ,
            'type'              => 'number' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => 0 ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'default_value'     => 4 ,
            'placeholder'       => '' ,
            'prepend'           => '' ,
            'append'            => '' ,
            'min'               => 0 ,
            'max'               => 10 ,
            'step'              => 1 ,
        ) ,
        array(
            'key'               => 'field_5cbe127da6c59' ,
            'label'             => 'Custom Slider' ,
            'name'              => 'custom_slider' ,
            'type'              => 'repeater' ,
            'instructions'      => '' ,
            'required'          => 0 ,
            'conditional_logic' => array(
                array(
                    array(
                        'field'    => 'field_5cbe0ff7a6c56' ,
                        'operator' => '==' ,
                        'value'    => 'custom' ,
                    ) ,
                ) ,
            ) ,
            'wrapper'           => array(
                'width' => '' ,
                'class' => '' ,
                'id'    => '' ,
            ) ,
            'collapsed'         => 'field_5cbe13064ca7a' ,
            'min'               => 0 ,
            'max'               => 0 ,
            'layout'            => 'row' ,
            'button_label'      => '' ,
            'sub_fields'        => array(
                array(
                    'key'               => 'field_5cbe13064ca7a' ,
                    'label'             => 'Title' ,
                    'name'              => 'title' ,
                    'type'              => 'text' ,
                    'instructions'      => '' ,
                    'required'          => 0 ,
                    'conditional_logic' => 0 ,
                    'wrapper'           => array(
                        'width' => '' ,
                        'class' => '' ,
                        'id'    => '' ,
                    ) ,
                    'default_value'     => '' ,
                    'placeholder'       => '' ,
                    'prepend'           => '' ,
                    'append'            => '' ,
                    'maxlength'         => '' ,
                ) ,
                array(
                    'key'               => 'field_5cbe13234ca7b' ,
                    'label'             => 'Description' ,
                    'name'              => 'description' ,
                    'type'              => 'textarea' ,
                    'instructions'      => '' ,
                    'required'          => 0 ,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_5d2781b83ad7c' ,
                                'operator' => '==' ,
                                'value'    => 'normal' ,
                            ) ,
                        ) ,
                    ) ,
                    'wrapper'           => array(
                        'width' => '' ,
                        'class' => '' ,
                        'id'    => '' ,
                    ) ,
                    'default_value'     => '' ,
                    'placeholder'       => '' ,
                    'maxlength'         => '' ,
                    'rows'              => '' ,
                    'new_lines'         => 'br' ,
                ) ,

                array(
                    'key'               => 'field_5d7abd1a8e8e9' ,
                    'label'             => 'Link' ,
                    'name'              => 'links' ,
                    'type'              => 'post_object' ,
                    'instructions'      => '' ,
                    'required'          => 1 ,
                    'conditional_logic' => 0 ,
                    'wrapper'           => array(
                        'width' => '' ,
                        'class' => '' ,
                        'id'    => '' ,
                    ) ,
                    'post_type'         => array(
                        0 => 'page' ,
                        1 => 'mavy-portfolio' ,
                        2 => 'post' ,
                    ) ,
                    'taxonomy'          => '' ,
                    'allow_null'        => 0 ,
                    'multiple'          => 0 ,
                    'return_format'     => 'object' ,
                    'ui'                => 1 ,
                ) ,
                array(
                    'key'               => 'field_5cbe14f698ce1' ,
                    'label'             => 'Image' ,
                    'name'              => 'image' ,
                    'type'              => 'image' ,
                    'instructions'      => '' ,
                    'required'          => 0 ,
                    'conditional_logic' => 0 ,
                    'wrapper'           => array(
                        'width' => '' ,
                        'class' => '' ,
                        'id'    => '' ,
                    ) ,
                    'return_format'     => 'id' ,
                    'preview_size'      => 'thumbnail' ,
                    'library'           => 'all' ,
                    'min_width'         => '' ,
                    'min_height'        => '' ,
                    'min_size'          => '' ,
                    'max_width'         => '' ,
                    'max_height'        => '' ,
                    'max_size'          => '' ,
                    'mime_types'        => '' ,
                ) ,
            ) ,
        ) ,
    ) ,
    'location'              => array(
        array(
            array(
                'param'    => 'page_template' ,
                'operator' => '==' ,
                'value'    => 'page-slider.php' ,
            ) ,
        ) ,
    ) ,
    'menu_order'            => 0 ,
    'position'              => 'normal' ,
    'style'                 => 'default' ,
    'label_placement'       => 'top' ,
    'instruction_placement' => 'label' ,
    'hide_on_screen'        => array(
        0  => 'the_content' ,
        1  => 'excerpt' ,
        2  => 'discussion' ,
        3  => 'comments' ,
        4  => 'revisions' ,
        5  => 'author' ,
        6  => 'format' ,
        7  => 'page_attributes' ,
        8  => 'featured_image' ,
        9  => 'categories' ,
        10 => 'tags' ,
        11 => 'send-trackbacks' ,
    ) ,
    'active'                => true ,
    'description'           => '' ,
) );

