<?php
acf_add_local_field_group(array(
    'key' => 'group_5d88e6513d7e8',
    'title' => 'Option Work Templete',
    'fields' => array(
        array(
            'key' => 'field_5d88e651517de',
            'label' => 'option',
            'name' => 'option',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5d277d7783e23',
                1 => 'field_5d7816181c1b8',
                2 => 'field_5d2784225f454',
                3 => 'field_5d2781b83ad7c',
                4 => 'field_5d277f7383e24',
                5 => 'field_5d28e73b57a3d',
                6 => 'field_5d2781a091f9a',
                7 => 'field_5d7abee14551e',
                8 => 'field_5d7abd1a8f4d6',
                9 => 'field_5d7abdf68f4d7',
                10 => 'field_5d7abe248f4d8',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'page-works.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
